language: php

matrix:
  include:
    - php: 5.6
      env: PHPUNIT_VERSION=5.7.*
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update; fi;
  - composer update
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
